# CHECKPOINT 2 TODO
Submit a jupyter notebook file (.ipynb) on Gradescope with:

● (5 points) Data preprocessing:
(a) import,
(b) parse (e.g., convert strings to ints),
(c) organize (e.g., set up a database or a pandas DataFrame).

● (20 points) Basic data exploration and summary statistics
  
  ○ You must present three conclusions using at least three different statistical methods including hypothesis testing.
  
  ■ For example: What are the main characteristics of your dataset? How
many features and entries are there? Is a feature over-represented? Are
features correlated? Are there outliers? Identify the attributes that will
affect your choice of primary analysis technique. Etcetera.

○ For each method, you must have at least one gorgeous plot.

# IMPORTS

In [1]:
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

# IMPORT DATASET

In [2]:
df = pd.read_csv("/content/fifa21 raw data v2.csv")
display(df.head())
print(df.dtypes)

/tmp/ipykernel_23442/781647240.py:1: DtypeWarning: Columns (76) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/content/fifa21 raw data v2.csv")

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,Contract,Positions,Height,Weight,Preferred Foot,BOV,Best Position,Joined,Loan Date End,Value,Wage,Release Clause,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,Dribbling,Curve,FK Accuracy,Long Passing,Ball Control,Movement,Acceleration,Sprint Speed,Agility,Reactions,Balance,Power,Shot Power,Jumping,Stamina,Strength,Long Shots,Mentality,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Defending,Marking,Standing Tackle,Sliding Tackle,Goalkeeping,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,Total Stats,Base Stats,W/F,SM,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/210006/,Argentina,33,93,93,\n\n\n\nFC Barcelona,2004 ~ 2021,"RW, ST, CF",170cm,72kg,Left,93,RW,"Jul 1, 2004",NaN,€103.5M,€560K,€138.4M,429,85,95,70,91,88,470,96,93,94,91,96,451,91,80,91,94,95,389,86,68,72,69,94,347,44,40,93,95,75,96,91,32,35,24,54,6,11,15,14,8,2231,466,4 ★,4★,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-santos-aveiro/210006/,Portugal,35,92,92,\n\n\n\nJuventus,2018 ~ 2022,"ST, LW",187cm,83kg,Right,92,ST,"Jul 10, 2018",NaN,€63M,€220K,€75.9M,437,84,95,90,82,86,414,88,81,76,77,92,431,87,91,87,95,71,444,94,95,84,78,93,353,63,29,95,82,84,95,84,28,32,24,58,7,11,15,14,11,2221,464,4 ★,5★,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,\n\n\n\nAtlético Madrid,2014 ~ 2023,GK,188cm,87kg,Right,91,GK,"Jul 16, 2014",NaN,€120M,€125K,€159.4M,95,13,11,15,43,13,109,12,13,14,40,30,307,43,60,67,88,49,268,59,78,41,78,12,140,34,19,11,65,11,68,57,27,12,18,437,87,92,78,90,90,1413,489,3 ★,1★,Medium,Medium,3 ★,87,92,78,90,52,90,150
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyne/210006/,Belgium,29,91,91,\n\n\n\nManchester City,2015 ~ 2023,"CAM, CM",181cm,70kg,Right,91,CAM,"Aug 30, 2015",NaN,€129M,€370K,€161M,407,94,82,55,94,82,441,88,85,83,93,92,398,77,76,78,91,76,408,91,63,89,74,91,408,76,66,88,94,84,91,186,68,65,53,56,15,13,5,10,13,2304,485,5 ★,4★,High,High,4 ★,76,86,93,88,64,78,207
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silva-santos-jr/210006/,Brazil,28,91,91,\n\n\n\nParis Saint-Germain,2017 ~ 2022,"LW, CAM",175cm,68kg,Right,91,LW,"Aug 3, 2017",NaN,€132M,€270K,€166.5M,408,85,87,62,87,87,448,95,88,89,81,95,453,94,89,96,91,83,357,80,62,81,50,84,356,51,36,87,90,92,93,94,35,30,29,59,9,9,15,15,11,2175,451,5 ★,5★,High,Medium,5 ★,91,85,86,94,36,59,595

ID                   int64
Name                object
LongName            object
photoUrl            object
playerUrl           object
Nationality         object
Age                  int64
↓OVA                 int64
POT                  int64
Club                object
Contract            object
Positions           object
Height              object
Weight              object
Preferred Foot      object
BOV                  int64
Best Position       object
Joined              object
Loan Date End       object
Value               object
Wage                object
Release Clause      object
Attacking            int64
Crossing             int64
Finishing            int64
Heading Accuracy     int64
Short Passing        int64
Volleys              int64
Skill                int64
Dribbling            int64
Curve                int64
FK Accuracy          int64
Long Passing         int64
Ball Control         int64
Movement             int64
Acceleration         int64
Sprint Speed         int64
Agility              int64
Reactions            int64
Balance              int64
Power                int64
Shot Power           int64
Jumping              int64
Stamina              int64
Strength             int64
Long Shots           int64
Mentality            int64
Aggression           int64
Interceptions        int64
Positioning          int64
Vision               int64
Penalties            int64
Composure            int64
Defending            int64
Marking              int64
Standing Tackle      int64
Sliding Tackle       int64
Goalkeeping          int64
GK Diving            int64
GK Handling          int64
GK Kicking           int64
GK Positioning       int64
GK Reflexes          int64
Total Stats          int64
Base Stats           int64
W/F                 object
SM                  object
A/W                 object
D/W                 object
IR                  object
PAC                  int64
SHO                  int64
PAS                  int64
DRI                  int64
DEF                  int64
PHY                  int64
Hits                object
dtype: object

# CLEAN DATASET

In [3]:
# Convert Height to centimeters
display(df["Height"].unique())

def convert_height(value):
  if "cm" in value:
    return int(value.replace("cm", ""))
  else:
    h = value.split("'")
    feet = int(h[0])
    inches = int(h[1].replace('"', ""))
    return round((feet * 30.48) + (inches * 2.54), 2)

df["Height"] = df["Height"].apply(convert_height)

display(df["Height"].unique())

array(['170cm', '187cm', '188cm', '181cm', '175cm', '184cm', '191cm',
       '178cm', '193cm', '185cm', '199cm', '173cm', '168cm', '176cm',
       '177cm', '183cm', '180cm', '189cm', '179cm', '195cm', '172cm',
       '182cm', '186cm', '192cm', '165cm', '194cm', '167cm', '196cm',
       '163cm', '190cm', '174cm', '169cm', '171cm', '197cm', '200cm',
       '166cm', '6\'2"', '164cm', '198cm', '6\'3"', '6\'5"', '5\'11"',
       '6\'4"', '6\'1"', '6\'0"', '5\'10"', '5\'9"', '5\'6"', '5\'7"',
       '5\'4"', '201cm', '158cm', '162cm', '161cm', '160cm', '203cm',
       '157cm', '156cm', '202cm', '159cm', '206cm', '155cm'], dtype=object)

array([170.  , 187.  , 188.  , 181.  , 175.  , 184.  , 191.  , 178.  ,
       193.  , 185.  , 199.  , 173.  , 168.  , 176.  , 177.  , 183.  ,
       180.  , 189.  , 179.  , 195.  , 172.  , 182.  , 186.  , 192.  ,
       165.  , 194.  , 167.  , 196.  , 163.  , 190.  , 174.  , 169.  ,
       171.  , 197.  , 200.  , 166.  , 187.96, 164.  , 198.  , 190.5 ,
       195.58, 180.34, 193.04, 185.42, 182.88, 177.8 , 175.26, 167.64,
       170.18, 162.56, 201.  , 158.  , 162.  , 161.  , 160.  , 203.  ,
       157.  , 156.  , 202.  , 159.  , 206.  , 155.  ])

In [4]:
# Convert Weight to pounds
display(df["Weight"].unique())

def convert_weight(value):
  if "lbs" in value:
    return int(value.replace("lbs", ""))
  else:
    return round(int(value.replace("kg", ""))*2.20462, 2)

df["Weight"] = df["Weight"].apply(convert_weight)
display(df["Weight"].unique())

array(['72kg', '83kg', '87kg', '70kg', '68kg', '80kg', '71kg', '91kg',
       '73kg', '85kg', '92kg', '69kg', '84kg', '96kg', '81kg', '82kg',
       '75kg', '86kg', '89kg', '74kg', '76kg', '64kg', '78kg', '90kg',
       '66kg', '60kg', '94kg', '79kg', '67kg', '65kg', '59kg', '61kg',
       '93kg', '88kg', '97kg', '77kg', '62kg', '63kg', '95kg', '100kg',
       '58kg', '183lbs', '179lbs', '172lbs', '196lbs', '176lbs', '185lbs',
       '170lbs', '203lbs', '168lbs', '161lbs', '146lbs', '130lbs',
       '190lbs', '174lbs', '148lbs', '165lbs', '159lbs', '192lbs',
       '181lbs', '139lbs', '154lbs', '157lbs', '163lbs', '98kg', '103kg',
       '99kg', '102kg', '56kg', '101kg', '57kg', '55kg', '104kg', '107kg',
       '110kg', '53kg', '50kg', '54kg', '52kg'], dtype=object)

array([158.73, 182.98, 191.8 , 154.32, 149.91, 176.37, 156.53, 200.62,
       160.94, 187.39, 202.83, 152.12, 185.19, 211.64, 178.57, 180.78,
       165.35, 189.6 , 196.21, 163.14, 167.55, 141.1 , 171.96, 198.42,
       145.5 , 132.28, 207.23, 174.16, 147.71, 143.3 , 130.07, 134.48,
       205.03, 194.01, 213.85, 169.76, 136.69, 138.89, 209.44, 220.46,
       127.87, 183.  , 179.  , 172.  , 196.  , 176.  , 185.  , 170.  ,
       203.  , 168.  , 161.  , 146.  , 130.  , 190.  , 174.  , 148.  ,
       165.  , 159.  , 192.  , 181.  , 139.  , 154.  , 157.  , 163.  ,
       216.05, 227.08, 218.26, 224.87, 123.46, 222.67, 125.66, 121.25,
       229.28, 235.89, 242.51, 116.84, 110.23, 119.05, 114.64])

In [5]:
"""
'Value', 'Wage' and "Release Clause' are object columns. Convert numerical
Value               object
Wage                object
Release Clause      object
"""
display(df["Value"].head())
display(df["Wage"].head())
display(df["Release Clause"].head())

def convert_money(value):
  if "M" in value:
    m = value[1:-1]
    return round(float(m)*1000000, 2)
  elif "K" in value:
    k = value[1:-1]
    return round(float(k)*1000, 2)
  else:
    return 0

df["Value"] = df["Value"].apply(convert_money)
df["Wage"] = df["Wage"].apply(convert_money)
df["Release Clause"] = df["Release Clause"].apply(convert_money)

display(df["Value"].head())
display(df["Wage"].head())
display(df["Release Clause"].head())

0    €103.5M
1       €63M
2      €120M
3      €129M
4      €132M
Name: Value, dtype: object

0    €560K
1    €220K
2    €125K
3    €370K
4    €270K
Name: Wage, dtype: object

0    €138.4M
1     €75.9M
2    €159.4M
3      €161M
4    €166.5M
Name: Release Clause, dtype: object

0    103500000.0
1     63000000.0
2    120000000.0
3    129000000.0
4    132000000.0
Name: Value, dtype: float64

0    560000.0
1    220000.0
2    125000.0
3    370000.0
4    270000.0
Name: Wage, dtype: float64

0    138400000.0
1     75900000.0
2    159400000.0
3    161000000.0
4    166500000.0
Name: Release Clause, dtype: float64

In [6]:
# Some columns have 'star' characters. Remove and convert to integer
star_cols = [col for col in df.columns if df[col].astype(str).str.contains("★").any()]
print(star_cols)
for col in star_cols:
  df[col] = df[col].str.replace("★", "").astype(int)
  print(df[col].head())

['W/F', 'SM', 'IR']
0    4
1    4
2    3
3    5
4    5
Name: W/F, dtype: int64
0    4
1    5
2    1
3    4
4    5
Name: SM, dtype: int64
0    5
1    5
2    3
3    4
4    5
Name: IR, dtype: int64

In [7]:
# Remove columns that have "\n" at the start
col_extra_line = [col for col in df.columns if df[col].astype(str).str.startswith("\n").any()]

for col in col_extra_line:
  df[col] = df[col].str.lstrip("\n")

display(df.head())

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,Contract,Positions,Height,Weight,Preferred Foot,BOV,Best Position,Joined,Loan Date End,Value,Wage,Release Clause,Attacking,Crossing,Finishing,Heading Accuracy,Short Passing,Volleys,Skill,Dribbling,Curve,FK Accuracy,Long Passing,Ball Control,Movement,Acceleration,Sprint Speed,Agility,Reactions,Balance,Power,Shot Power,Jumping,Stamina,Strength,Long Shots,Mentality,Aggression,Interceptions,Positioning,Vision,Penalties,Composure,Defending,Marking,Standing Tackle,Sliding Tackle,Goalkeeping,GK Diving,GK Handling,GK Kicking,GK Positioning,GK Reflexes,Total Stats,Base Stats,W/F,SM,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/210006/,Argentina,33,93,93,FC Barcelona,2004 ~ 2021,"RW, ST, CF",170.0,158.73,Left,93,RW,"Jul 1, 2004",NaN,103500000.0,560000.0,138400000.0,429,85,95,70,91,88,470,96,93,94,91,96,451,91,80,91,94,95,389,86,68,72,69,94,347,44,40,93,95,75,96,91,32,35,24,54,6,11,15,14,8,2231,466,4,4,Medium,Low,5,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-santos-aveiro/210006/,Portugal,35,92,92,Juventus,2018 ~ 2022,"ST, LW",187.0,182.98,Right,92,ST,"Jul 10, 2018",NaN,63000000.0,220000.0,75900000.0,437,84,95,90,82,86,414,88,81,76,77,92,431,87,91,87,95,71,444,94,95,84,78,93,353,63,29,95,82,84,95,84,28,32,24,58,7,11,15,14,11,2221,464,4,5,High,Low,5,89,93,81,89,35,77,562
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,Atlético Madrid,2014 ~ 2023,GK,188.0,191.80,Right,91,GK,"Jul 16, 2014",NaN,120000000.0,125000.0,159400000.0,95,13,11,15,43,13,109,12,13,14,40,30,307,43,60,67,88,49,268,59,78,41,78,12,140,34,19,11,65,11,68,57,27,12,18,437,87,92,78,90,90,1413,489,3,1,Medium,Medium,3,87,92,78,90,52,90,150
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyne/210006/,Belgium,29,91,91,Manchester City,2015 ~ 2023,"CAM, CM",181.0,154.32,Right,91,CAM,"Aug 30, 2015",NaN,129000000.0,370000.0,161000000.0,407,94,82,55,94,82,441,88,85,83,93,92,398,77,76,78,91,76,408,91,63,89,74,91,408,76,66,88,94,84,91,186,68,65,53,56,15,13,5,10,13,2304,485,5,4,High,High,4,76,86,93,88,64,78,207
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silva-santos-jr/210006/,Brazil,28,91,91,Paris Saint-Germain,2017 ~ 2022,"LW, CAM",175.0,149.91,Right,91,LW,"Aug 3, 2017",NaN,132000000.0,270000.0,166500000.0,408,85,87,62,87,87,448,95,88,89,81,95,453,94,89,96,91,83,357,80,62,81,50,84,356,51,36,87,90,92,93,94,35,30,29,59,9,9,15,15,11,2175,451,5,5,High,Medium,5,91,85,86,94,36,59,595

# BASIC DATA EXPLORATION AND DATA ANALYSIS

In [9]:
# Choose 3 different statistical tests (1 tail t test, anova, etc), 1 visualization per test
# choose whatever features we want for our hypothesis test